services:
  - type: web
    name: blackletter
    region: oregon
    plan: free
    branch: main
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: BACKEND_URL
        value: https://blackletter-backend.onrender.com/review
