services:
  - type: web
    name: blackletter
    env: python
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt
      cd ../frontend && npm install && npm run build
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
