services:
  # Backend API Service
  - type: web
    name: blackletter-backend
    rootDir: backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
      # Add your environment variables here
      # - key: OPENAI_API_KEY
      #   sync: false
      # - key: GOOGLE_API_KEY
      #   sync: false

  # Frontend Service
  - type: web
    name: blackletter-frontend
    rootDir: frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NEXT_PUBLIC_API_URL
        value: https://blackletter-backend.onrender.com
      - key: PORT
        value: 3000
