services:
  - type: web
    name: blackletter
    region: oregon
    plan: free
    branch: main
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      cd src/backend
      pip install -r requirements.txt
    startCommand: |
      cd src
      export PYTHONPATH=$PYTHONPATH:$PWD
      uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: BACKEND_URL
        value: https://blackletter-backend.onrender.com/review
