services:
  - type: web
    name: blackletter
    env: python
    buildCommand: |
      # Install python dependencies
      pip install -r requirements.txt
      # Install nodejs and npm
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs
      # Build frontend
      cd frontend
      npm install
      npm run build
      cd ..
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
