services:
  - type: web
    name: blackletter-backend
    region: oregon
    plan: free
    branch: main
    runtime: python
    root: backend
  buildCommand: pip install -r backend/requirements.txt
  startCommand: gunicorn -k uvicorn.workers.UvicornWorker backend.main:app --bind 0.0.0.0:$PORT --workers 2
  healthCheckPath: /health
