services:
  - type: web
    name: blackletter-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health

  - type: web
    name: blackletter-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start -- -p $PORT
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://blackletter.onrender.com
