[tool.poetry]
name = "blackletter"
version = "0.1.0"
description = ""

[tool.poetry.dependencies]
python = "^3.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"