name: Assurance Eval
on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'rules/**'
      - '.github/workflows/eval-assurance.yml'
  workflow_dispatch:

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run assurance:eval
      - name: Upload Assurance Card
        uses: actions/upload-artifact@v4
        with:
          name: assurance-card
          path: artifacts/**
