name: Release Notes
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate changelog
        run: |
          echo "## Release $GITHUB_REF_NAME" > RELEASE_NOTES.md
          git log --pretty=format:'- %s (%h)' $(git describe --tags --abbrev=0 --tags `git rev-list --tags --max-count=1`)..HEAD >> RELEASE_NOTES.md || true
      - uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: RELEASE_NOTES.md
