name: SLA Timer
on:
  issues:
    types: [opened, edited, labeled]
  schedule:
    - cron: '0 9 * * 1-5'  # business days 09:00 UTC

jobs:
  sla:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SLA labeling
        uses: actions-ecosystem/action-add-labels@v1
        if: contains(github.event.issue.labels.*.name, 'assurance') && contains(github.event.issue.labels.*.name, 'sla:10d')
        with:
          labels: "sla:in-progress"
      # NOTE: In a real setup, you'd calculate business days and flip to sla:breach when overdue.
