name: Status Page
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run status:generate
      - name: Upload status.json
        uses: actions/upload-artifact@v4
        with:
          name: status
          path: public/status.json
