name: RAG Evaluation

on:
  push:
  pull_request:

jobs:
  rag-eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run RAG evaluation
        shell: pwsh
        run: ./scripts/rag_eval.ps1
